#!/bin/bash


while read -r line; do
    source lconfig

    case "$line" in
        R*)
            right=${line#?}
            ;;
        W*)
            # bspwm internal states
            wm=""
            IFS=':'
            set -- ${line#?}

            while [ $# -gt 0 ]; do
                item=$1
                name=${item#?}

                case "$item" in
                    O*)
                        # Focused Occupied
                        FG=$COLOR_OCCUPIED_FOCUSED_FG
                        BG=$COLOR_OCCUPIED_FOCUSED_BG
                        UD=$COLOR_OCCUPIED_FOCUSED_UD

                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                    o*)
                        # Occupied
                        FG=$COLOR_OCCUPIED_FG
                        BG=$COLOR_OCCUPIED_BG
                        UD=$COLOR_OCCUPIED_UD

                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                    F*)
                        # Focused Free
                        FG=$COLOR_FREE_FOCUSED_FG
                        BG=$COLOR_FREE_FOCUSED_BG
                        UD=$COLOR_FREE_FOCUSED_UD

                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                    f*)
                        # Free
                        FG=$COLOR_FREE_FG
                        BG=$COLOR_FREE_BG
                        UD=$COLOR_FREE_UD
                        
                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                    U*)
                        # Focused Urgent
                        FG=$COLOR_URGEN_FOCUSED_FG
                        BG=$COLOR_URGEN_FOCUSED_BG
                        UD=$COLOR_URGEN_FOCUSED_UD

                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                    u*)
                        # Urgent
                        FG=$COLOR_URGEN_FG
                        BG=$COLOR_URGEN_BG
                        UD=$COLOR_URGEN_UD

                        wm="$wm %{+u}%{F$FG}%{B$BG}%{U$UD}     %{U-}%{B-}%{F-}%{u-} "
                        ;;
                esac

                shift
            done
            ;;
    esac

    sep=" "
    echo "%{l}$wm%{r}$right"
done
