#!/bin/bash

source lconfig

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

# Workspaces
bspc control --subscribe > "$PANEL_FIFO" &

# Clock on the right
while true; do
    echo "R$(date +"%a %{Fwhite}%I:%M %p%{F-}")" > "$PANEL_FIFO"
    sleep 10
done &

cat "$PANEL_FIFO" \
    | "$(dirname $0)/lpanel_bar" \
    | lemonbar -p \
               -f "$PANEL_FONT" \
               -F "$PANEL_FG" \
               -B "$PANEL_BG" \
               -U "$PANEL_UD" \
               -u "$PANEL_UNDERLINE_WIDTH"
