#!/bin/bash

# Configurations ====================================================

PANEL_FONT_FAMILY="Ubuntu Condensed:size=13:antialias=true:hinting=true"
PANEL_COLOR_FG='#969696'
PANEL_COLOR_BG='#000000'
PANEL_X_POSITION=0
PANEL_Y_POSITION=0
#PANEL_HEIGHT=15
PANEL_WIDTH=
COMMAND_LIST="onstart=lower"

# Init components ===================================================

source "/etc/os-release"

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

export PANEL_FIFO="/tmp/panel-fifo"

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

#bspc config top_padding $PANEL_HEIGHT
bspc subscribe report > "$PANEL_FIFO" &
#xtitle -sf 'T%s' > "$PANEL_FIFO" &
echo "L^ca(1, "dsysinfo")^fg(white)$NAME^fg() $(uname -r)^ca()"> "$PANEL_FIFO" &

while true; do
    echo "R^ca(1, "ddate")$(date +"%a ^fg(white) %I:%M %p^fg()")^ca()" >"$PANEL_FIFO"
    #echo "M$($HOME/.config/bspwm/panel/media_controller)" > "$PANEL_FIFO"
    sleep 05
done &

# Launch panel ======================================================

cat "$PANEL_FIFO" \
    | "$(dirname "$0")/panel_bar" \
    | dzen2 -e "button2=;" \
            -fg "$PANEL_COLOR_FG" \
            -bg "$PANEL_COLOR_BG" \
            -x  "$PANEL_X_POSITION" \
            -y  "$PANEL_Y_POSITION" \
            -fn "$PANEL_FONT_FAMILY" \
            -h  "$PANEL_HEIGHT" \
            -w  "$PANEL_WIDTH" \
            -e  "$COMMAND_LIST"
wait
