#!/bin/bash

# Panel configs {{{
panel_type="lemonbar"
panel_wm_name="bspwm"
panel_x=0
panel_y=0
panel_width=
panel_height=
panel_font_family="Inconsolata for Powerline:size=9"
#}}}

# Symbols {{{
sym_left_sep=''
sym_left_sep_alt=''
sym_right_sep=''
sym_right_sep_alt=''
sym_branch=''
sym_readonly=''
sym_line_number=''
sym_paste='Þ'
sym_whitespace='Ξ'
# }}} 

# Panel Colors

## Global {{{
color_global_bg='#1B1D1E' # Nero
color_global_fg='#5D887E' # Opal

color_global_bg_alt="2B2B2B" # Nero
color_global_blue='#1D90CD' # Dark Blue
color_global_red='#d64937' # Red-Orange? Somehow
color_global_yellow='#FFFF7F' # Light Yellow
color_global_black='#000000' # Black
color_global_white='#FFFFFF' # White
## }}}

## Monitors {{{
color_monitor_active_bg=
color_monitor_active_fg=

color_monitor_inactive_bg=
color_monitor_inactive_fg=
## }}}

## Workspaces {{{
color_focused_occupied_bg="${color_global_blue}"
color_focused_occupied_fg="${color_global_white}"

color_focused_free_bg="${color_global_yellow}"
color_focused_free_fg="${color_global_black}"

color_focused_urgent_bg="${color_global_red}"
color_focused_urgent_fg="${color_global_fg}"

color_occupied_bg="${color_global_bg}"
color_occupied_fg="${color_global_white}"

color_free_bg="${color_global_bg}"
color_free_fg="${color_global_fg}"

color_urgent_bg="${color_global_fg}"
color_urgent_fg="${color_global_white}"
## }}}

## Extras {{{
color_title_bg=
color_title_fg=

color_status_bg=
color_status_fg=

color_layout_bg="${color_global_fg}"
color_layout_fg='#A3A6AB'
## }}}

# Widgets {{{

## Sysinfo {{{
color_widget_sysinfo_fg='#FFFFFF' # white
color_widget_sysinfo_bg="${color_global_bg}"
## }}}

## Clock {{{
color_widget_clock_fg='#000000' # black
color_widget_clock_bg='#FFFFFF' # white
## }}}

# }}}
