#!/bin/bash
PANEL_FIFO=/tmp/panel-fifo
PANEL_HEIGHT=24
PANEL_FONT="Unbuntu Mono:size=10"
PANEL_WM_NAME="bspwm_panel"
COLOR_DEFAULT_FG='#969696'
COLOR_DEFAULT_BG='#000000'

export PANEL_FIFO PANEL_FONT PANEL_HEIGHT PANEL_WM_NAME COLOR_DEFAULT_FG COLOR_DEFAULT_BG

#if xdo id -a "$PANEL_WM_NAME" > /dev/null ; then
    #printf "%s\n" "The panel is already running." >&2
    #exit 1
#fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe report > "$PANEL_FIFO" &
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &

#source "$(dirname $0)/lemonbar_panel_colors"

"$(dirname $0)/lemonbar_panel_bar" < "$PANEL_FIFO" \
    | lemonbar -a 32 \
               -f "$PANEL_FONT" \
               -F "$COLOR_DEFAULT_FG" \
               -B "$COLOR_DEFAULT_BG"\
    | bash &

wid=$(xdo id -a "$PANEL_WM_NAME")

#tries_left=20
#while [ -z "$wid" -a "$tries_left" -gt 0 ] ; do
    #sleep 0.05
    #wid=$(xdo id -a "$PANEL_WM_NAME")
    #tries_left=$((tries_left - 1))
#done
#[ -n "$wid" ] && xdo above -t "$(xdo id -N Bspwm -n root | sort | head -n 1)" "$wid"

wait
