#!/bin/bash

bspc config border_width  2
bspc config window_gap   10

bspc config top_padding  21

bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_by_distance           true

bspc config normal_border_color         "#033480"
bspc config active_border_color         "#00FFCC"
bspc config focused_border_color        "#1D90CD"
bspc config presel_feedback_color       "#1D90CD"
bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.1

bspc monitor -d SHELL WEB PUB MEDIA DEV FILE GAME SYNC DOC MISC

#
# Application-binding rules ---------------------
#

(

#
# 1. Shell
#



#
# 2. Web
#
bspc rule -a Chromium desktop=^2
bspc rule -a Firefox desktop=^2
bspc rule -a Thunderbird desktop=^2

#
# 3. Public
#
bspc rule -a \*:MessengerForDesktop desktop=^3
bpsc rule -a Telegram desktop=^3
bspc rule -a Caprine desktop=^3

#
# 4. Media
#
bspc rule -a smplayer desktop=^4

#
# 5. Dev
#
bspc rule -a qtcreator-bin desktop=^5
bspc rule -a QtCreator desktop=^5
bspc rule -a Unity desktop=^5
bspc rule -a MonoDevelop desktop=^5
bspc rule -a jetbrains-pycharm desktop=^5
bspc rule -a \*:sun-awt-X11-XFramePeer desktop=^5

#
# 6. File
#
bspc rule -a Nemo desktop=^6

#
# 7. Game
#
bspc rule -a Steam desktop=^7
bspc rule -a ppsspp desktop=^7 floating=on

#
# 8. Sync
#
bspc rule -a Deluge desktop=^8
bspc rule -a Uget-gtk desktop=^8

#
# 9. Doc
#
bspc rule -a loffice desktop=^9
bspc rule -a libreoffice desktop=^9
bspc rule -a libreoffice-startcenter desktop=^9
bspc rule -a libreoffice-writer desktop=^9
bspc rule -a libreoffice-calc desktop=^9
bspc rule -a libreoffice-impress desktop=^9
bspc rule -a libreoffice-draw desktop=^9
bspc rule -a libreoffice-impress desktop=^9
bspc rule -a libreoffice-math desktop=^9
bspc rule -a Evince desktop=^9

#
# 10. Misc
#
bspc rule -a Gimp desktop=^10
bspc rule -a Gimp-2.8 desktop=^10
bspc rule -a VirtualBox desktop=^10

#
# Other Application Rules
#
bspc rule -a Conky sticky=on manage=off fullscreen=true lower=true

notify-send "Bspwm" "External rules loaded"

) &

#
# Startup ---------------------------------------
#

sxhkd &
source $(dirname $0)/autostart &

# Launch panel
bash "$(dirname $0)/panel/panel"

