#!/bin/bash

# Environment
[[ -f ~/.Xresources ]] && xrdb ~/.Xresources
source ~/.profile

# Daemons & backgrounds
conky -q &
urxvtd --quiet --opendisplay --fork &
syndaemon -d -k -i 2 &

# Tray applications
copyq &
#insync start --no-custom-folder-icon &
fcitx &
mpDris2 &
thunderbird &

# Misc
unclutter &
numlockx on &
touchpad-script off &
devdocs-server &
archwiki-server &
